
name: Antithetical Parallels
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
encoding: "utf-8"
author:
  name: "TestSubjector"
url: https://testsubjector.github.io/
comments: true
highlighter: rouge

include:
- _pages

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  link:
    output: true
    permalink: /:collection/:title/
  misc:
    output: true
    permalink: /:collection/:title/
  feed:
    posts_limit: 20
