
name: Antithetical Parallels
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
encoding: "utf-8"
author:
  name: "TestSubjector" 

comments: true

include:
- _pages

plugins:
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  poetry:
    output: true
    permalink: /:collection/:title/

